#!/bin/bash
set -eu

IPC_PATH="/data/reth.ipc"
RETH_DATA_DIR=/data
RPC_PORT="${RPC_PORT:-8545}"
WS_PORT="${WS_PORT:-8546}"
AUTHRPC_PORT="${AUTHRPC_PORT:-8551}"
METRICS_PORT="${METRICS_PORT:-6060}"
DISCOVERY_PORT="${DISCOVERY_PORT:-30303}"
P2P_PORT="${P2P_PORT:-30303}"
ADDITIONAL_ARGS=""
BINARY="./base-reth-node"

if [[ -z "${RETH_CHAIN:-}" ]]; then
    echo "expected RETH_CHAIN to be set" 1>&2
    exit 1
fi

# Enable Flashblocks support if websocket URL is provided
if [[ -n "${RETH_FB_WEBSOCKET_URL:-}" ]]; then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS --websocket-url=$RETH_FB_WEBSOCKET_URL"
    echo "Enabling Flashblocks support with endpoint: $RETH_FB_WEBSOCKET_URL"
else
    echo "Running in vanilla node mode (no Flashblocks URL provided)"
fi


ADDITIONAL_ARGS="$ADDITIONAL_ARGS \
  --stages.headers.downloader-max-concurrent-requests 300 \
  --stages.headers.downloader-request-limit 2000 \
  --stages.headers.downloader-max-buffered-responses 200 \
  --stages.headers.commit-threshold 50000 \
  --stages.bodies.downloader-max-concurrent-requests 300 \
  --stages.bodies.downloader-request-limit 500 \
  --stages.bodies.downloader-stream-batch-size 5000 \
  --stages.bodies.downloader-max-buffered-blocks-size-bytes 8589934592 \
  --stages.sender-recovery.commit-threshold 10000000 \
  --stages.execution.max-blocks 2000000 \
  --stages.execution.max-changes 20000000 \
  --stages.execution.max-cumulative-gas 5000000000 \
  --stages.execution.max-duration 30m \
  --stages.account-hashing.commit-threshold 500000 \
  --stages.storage-hashing.commit-threshold 500000 \
  --stages.merkle.incremental-threshold 10000 \
  --stages.transaction-lookup.chunk-size 10000000 \
  --peers.connection-info.max-outbound 200 \
  --peers.connection-info.max-concurrent-outbound-dials 50 \
  --sessions.session-command-buffer 64 \
  --sessions.session-event-buffer 512"

# Add pruning for base
if [[ "${RETH_PRUNING_ARGS+x}" = x ]]; then
    echo "Adding pruning arguments: $RETH_PRUNING_ARGS"
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS $RETH_PRUNING_ARGS"
fi

mkdir -p "$RETH_DATA_DIR"
echo "Starting reth with additional args: $ADDITIONAL_ARGS"
echo "$OP_NODE_L2_ENGINE_AUTH_RAW" > "$OP_NODE_L2_ENGINE_AUTH"

exec "$BINARY" node \
  -vvv \
  --datadir="$RETH_DATA_DIR" \
  --log.stdout.format json \
  --ws \
  --ws.origins="*" \
  --ws.addr=0.0.0.0 \
  --ws.port="$WS_PORT" \
  --ws.api=web3,debug,eth,net,txpool \
  --http \
  --http.corsdomain="*" \
  --http.addr=0.0.0.0 \
  --http.port="$RPC_PORT" \
  --http.api=web3,debug,eth,net,txpool,miner \
  --ipcpath="$IPC_PATH" \
  --authrpc.addr=0.0.0.0 \
  --authrpc.port="$AUTHRPC_PORT" \
  --authrpc.jwtsecret="$OP_NODE_L2_ENGINE_AUTH" \
  --metrics=0.0.0.0:"$METRICS_PORT" \
  --max-outbound-peers=100 \
  --chain "$RETH_CHAIN" \
  --rollup.sequencer-http="$RETH_SEQUENCER_HTTP" \
  --rollup.disable-tx-pool-gossip \
  --discovery.port="$DISCOVERY_PORT" \
  --port="$P2P_PORT" \

  $ADDITIONAL_ARGS
